### ISSUE TITLE
Pantry Dashboard View

### ISSUE THREAD

**Issue by osori** [Scavenge-UW/Scavenge#12]
### Prototype
![image](https://user-images.githubusercontent.com/13430641/111924224-64157f00-8a71-11eb-872f-118ac28665cb.png)

### Description
e8525535c83e53a342d4f8ba293c67d2fcb4bc0c in `lq-adminview` includes `PantryAdminView` where admin can select between Pantry Dashboard View and Inventory View, as shown below:
![image](https://user-images.githubusercontent.com/13430641/111924492-e0f52880-8a72-11eb-93fa-a5b1d172e00a.png)

Start from this e8525535c83e53a342d4f8ba293c67d2fcb4bc0c commit in `lq-adminview` branch and implement `DashboardView.js` to work on the following tasks below. Feel free to create other necessary components as needed.

### Tasks
 
**5.1 View/Edit Food Pantry Description - Jason**
- [x]     5.1.1 Design and Implement a Card to display Food Pantry Description - **Done**
- [x]     5.1.2 Design and Implement a Form where User can edit the Food Pantry Description - **Done**
- [x]     5.1.3 Interact with the backend server to store the updated description - **Done**

**5.2 View/Edit Food Pantry’s Operating Hours - Andy**

- [x]     5.2.1 Design and Implement a Card to display Food Pantry’s Operating Hours
- [x]     5.2.2 Design and Implement a Form where User can edit  Food Pantry’s Operating Hours
- [x]     5.2.3 Interact with the backend server to store the updated operating hours - **in progress**

**5.3 Show User Reservations - Andy**

- [x]     5.3.1 Design a Card to display User Reservation Detail and two action buttons, “Mark as picked up” and “Cancel this reservation”
- [x]     5.3.2 Fetch User Reservations from API and display in Cards from 5.3.1

**5.4. General Layout Design Improvement (Aligning Components from 5.1, 5.2, and 5.3) - Andy**
- [ ] Fix any UI issues
